{{- if .Values.realm.import }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  dcs-realm.json: |-
{{ .Files.Get "files/dcs-realm.json" | indent 4 }}
{{- end }}
