{{- if .Values.federatedCatalogue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-federated-catalogue
spec:
  type: {{ .Values.federatedCatalogue.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.federatedCatalogue.service.port | default 8081 }}
      targetPort: http
  selector:
    app.kubernetes.io/name: federated-catalogue
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
