package auth

import (
	"context"
	"digital-contracting-service/internal/middleware"

	goa "goa.design/goa/v3/pkg"
	"goa.design/goa/v3/security"
)

// JWTAuthenticator implements the Auther interface generated by Goa for the
// "jwt" security scheme. Embed this struct in every service implementation so
// that the service satisfies the generated Auther interface.
//
// Usage:
//
//	type myService struct {
//	    auth.JWTAuthenticator
//	}
type JWTAuthenticator struct {
	Validator *middleware.OIDCValidator
}

// NewJWTAuthenticator returns a JWTAuthenticator backed by the given OIDC
// validator.
func NewJWTAuthenticator(v *middleware.OIDCValidator) JWTAuthenticator {
	return JWTAuthenticator{Validator: v}
}

// JWTAuth validates a JWT token via the OIDC provider and checks that the
// caller possesses at least one of the required scopes (Keycloak realm roles).
// It returns an enriched context with the caller's roles on success.
func (a JWTAuthenticator) JWTAuth(ctx context.Context, token string, scheme *security.JWTScheme) (context.Context, error) {
	if token == "" {
		return ctx, goa.PermanentError("unauthorized", "missing JWT token")
	}

	// Validate the token, check azp, and extract roles + username.
	info, err := a.Validator.ValidateToken(ctx, token)
	if err != nil {
		return ctx, goa.PermanentError("unauthorized", "invalid token: %s", err)
	}

	// If the endpoint declares required scopes, enforce at least one match.
	if len(scheme.RequiredScopes) > 0 {
		if !hasAnyRole(info.Roles, scheme.RequiredScopes) {
			return ctx, goa.PermanentError("forbidden", "insufficient permissions: requires one of %v", scheme.RequiredScopes)
		}
	}

	// Inject the validated identity into the context for downstream use.
	ctx = middleware.InjectAuthContext(ctx, info.Roles, info.Username, info.ParticipantID)
	return ctx, nil
}

// hasAnyRole returns true if roles contains at least one of the required roles.
func hasAnyRole(roles []string, required []string) bool {
	set := make(map[string]struct{}, len(roles))
	for _, r := range roles {
		set[r] = struct{}{}
	}
	for _, r := range required {
		if _, ok := set[r]; ok {
			return true
		}
	}
	return false
}
