apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
spec:
  type: ClusterIP
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ .Release.Name }}
